### ISSUE TITLE
Build fails ModuleNotFoundError: No module named 'skbuild'

### ISSUE THREAD

**Issue by sk1ll10** [allenai/ai2thor-docker#6]
Building the image in ubuntu 18.04 Kernel 5.4.0-51, Nvidia 450.80.02 fails on my machine atm

```
Step 9/13 : RUN pip3 install -r requirements.txt && python3 -c "import ai2thor.controller; ai2thor.controller.Controller(download_only=True)"
 ---> Running in 4258bdabdc29
Collecting ai2thor (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/53/03/4de4efd1858ecb4f4cbcaff1750452e59ad0607337bd1966694e95cbb1f9/ai2thor-2.4.22-py2.py3-none-any.whl (46kB)
Collecting flask (from ai2thor->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl (94kB)
Collecting aws-requests-auth (from ai2thor->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/af/11/5dc8be418e1d54bed15eaf3a7461797e5ebb9e6a34869ad750561f35fa5b/aws_requests_auth-0.4.3-py2.py3-none-any.whl
Collecting Pillow (from ai2thor->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a6/9c/829c74f7f7f129616dfb6f75afd72529f895d29db71c7aeb46b02fcfb26d/Pillow-8.0.0-cp36-cp36m-manylinux1_x86_64.whl (2.2MB)
Collecting progressbar2 (from ai2thor->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/25/8c/d28cd70b6e0b870a2d2a151bdbecf4c678199d31731edb44fc8035d3bb6d/progressbar2-3.53.1-py2.py3-none-any.whl
Collecting botocore (from ai2thor->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/15/53/f4eee30d48e0e495a1ec73ca1c8cc2b6090c378bdb226e42e8cac9278e1e/botocore-1.19.1-py2.py3-none-any.whl (6.7MB)
Collecting msgpack (from ai2thor->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c9/35/33aa1af0700d21beabdf74373f31c52c048be8ee082f98edbc37ba3ae956/msgpack-1.0.0-cp36-cp36m-manylinux1_x86_64.whl (274kB)
Collecting werkzeug>=0.15.0 (from ai2thor->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl (298kB)
Collecting pyyaml (from ai2thor->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz (269kB)
Collecting opencv-python (from ai2thor->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/38/a9/cd39fd25df434b5d9451dc266c12b72f68282a2b9bd5d7b4aa2d57d6c20e/opencv-python-4.4.0.44.tar.gz (88.9MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-askut9e5/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
`

**Comment by sk1ll10** [comment]
adding `RUN pip3 install --upgrade pip` to the dockerfile solved the issue

**Comment by sk1ll10** [comment]
Pull request submitted. Close when accepted.
