### ISSUE TITLE
No module named ai2thor_docker

### ISSUE THREAD

**Issue by astrosaeed** [allenai/ai2thor-docker#9]
I followed the instructions in the README, but when I run the example_agent.py, I get the error below:

> Traceback (most recent call last):
  File "example_agent.py", line 2, in <module>
    from ai2thor_docker.x_server import startx
ModuleNotFoundError: No module named 'ai2thor_docker'

The installation was working well and I didn't see any issues except for three warnings when Nvidia driver was being installed. 
Any ideas why `ai2thor_docker` is not recognized?

**Comment by ekolve** [comment]
Can you retry the latest commit on the ai2thor-docker repo? The example_agent.py has changed.

**Comment by astrosaeed** [comment]
Initially, I was using the latest commit and here is the error I got on a PC with 3070 TI GPU and Ubuntu 18.04:

> Traceback (most recent call last):
  File "example_agent.py", line 7, in <module>
    controller = ai2thor.controller.Controller(platform=ai2thor.platform.CloudRendering, scene='FloorPlan28')
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/controller.py", line 498, in __init__
    host=host,
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/controller.py", line 1292, in start
    self._start_unity_thread(env, width, height, unity_params, image_name)
  File "/usr/local/lib/python3.6/dist-packages/ai2thor/controller.py", line 1020, in _start_unity_thread
    raise Exception(message)
Exception: Unity process has exited - check Player.log for errors. Confirm that Vulkan is properly configured on this system using vulkan info from the vulkan-utils package. return code=-11


Then, I noticed that the example code on `README.md `file is a bit different than `example_agent.py`, so I used the example code that includes `startx()` function, and got the error below:

> Traceback (most recent call last):
File "example_agent.py", line 2, in
from ai2thor_docker.x_server import startx
ModuleNotFoundError: No module named 'ai2thor_docker'

I should note that, throughout the GPU driver installation process, I got these warnings but no errors:

> Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 495.29.05.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
WARNING: You specified the '--no-kernel-module' command line option, nvidia-installer will not install a kernel module as part of this driver installation, and it will not remove existing NVIDIA kernel modules not part of an earlier NVIDIA driver installation.  Please ensure that an NVIDIA kernel module matching this driver version is installed separately.
WARNING: nvidia-installer was forced to guess the X library path '/usr/lib' and X module path '/usr/lib/xorg/modules'; these paths were not queryable from the system.  If X fails to find the NVIDIA X driver module, please install the `pkg-config` utility and the X.Org SDK/development package for your distribution and reinstall the driver.
WARNING: Unable to find a suitable destination to install 32-bit compatibility libraries. Your system may not be set up for 32-bit compatibility. 32-bit compatibility files will not be installed; if you wish to install them, re-run the installation and set a valid directory with the --compat32-libdir option.

**Comment by Reagan1311** [comment]
@astrosaeed  I have exactly the same error and warningss, did you figure it out?

**Comment by astrosaeed** [comment]
> @astrosaeed I have exactly the same error and warnings, did you figure it out?

No, I could not. Let me know if you find anything.

**Comment by Chinartist** [comment]
@astrosaeed I have exactly the same error and warnings, did you figure it out now?
